print "Hello"
print "Bye"
print 
print "Hello"
print "Bye"print "Hello"
print "Bye"print "Hello"
print "Bye"print "Hello"
print "Bye"print "Hello"
print "Bye"print "Hello"
print "Bye"print "Hello"
print "Bye"print "Hello"
print "Bye"print "Hello"
print "Bye"print "Hello"
print "Bye"
10