---
- hosts: 127.0.0.1
  become: true
  tasks:  
    - apt: update_cache=yes  
    
    - name: Install a list of packages
      apt:
        name:
          - build-essential
          - manpages-dev
          - gdb
          - bison
          - autoconf
          - automake
          - cmake
          - libfftw3-dev

        state: present
        update_cache: yes 
    
        
    - name: Unarchive a gromacs file that needs to be downloaded 
      unarchive:
        src: http://ftp.gromacs.org/pub/gromacs/gromacs-2019.3.tar.gz
        dest: /home/codio/workspace/
        remote_src: yes
    
    - name: Create a directory build
      file:
        path: /home/codio/workspace/gromacs-2019.3/build
        state: directory
        mode: '0755'
        
    - apt: update_cache=yes
    
    - name: Setup environment variables 
      shell: 
        chdir: /home/codio/workspace/gromacs-2019.3/build/
        cmd: cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON
    
    - name: Make file
      shell: 
        chdir: /home/codio/workspace/gromacs-2019.3/build/
        cmd: make
      
    - name: Make check
      shell: 
        chdir: /home/codio/workspace/gromacs-2019.3/build/
        cmd: make check
      
    - name: install
      shell: 
        chdir: /home/codio/workspace/gromacs-2019.3/build/
        cmd: sudo make install
      
    - name: set compiler
      shell: 
        chdir: /home/codio/workspace/gromacs-2019.3/build/
        cmd: sudo cmake .. -DCMAKE_C_COMPILER=gcc
    
    - name: make source
      shell: 
        chdir: /home/codio/workspace/
        cmd: source /usr/local/gromacs/bin/GMXRC
      
    - name: start version
      shell: gmx pdb2gmx --version
    
